### ISSUE TITLE
example folder and question about 32bit 

### ISSUE THREAD

**Issue by davehorner** [nickbabcock/highwayhasher#65]
I'm still trying to understand how to host this from a browser. I will continue working towards this; just wondering if there are additional examples to include or suggestions.

Also, there's no discussion tab, so I'm adding it here. I'm interested in 32bit hashes. I understand the highway algorithm is 64bit minimum. It wouldn't need to be highway; something like crc32fast to provide the algorithm for a 32bit hash output? Do I fork and work a separate binding for crc32fast or extend highway or is it not a good idea for some reason?

**Comment by nickbabcock** [comment]
There are many ways to host this in the browser and there is no right way. Every build tool and target environment is different. What problem are you running into? If you have something specific in mind, we can chat about it.

If there is no build tool, the easiest way to add highwayhasher to the browser is through something like:

```html
<body>
  <script src="https://cdn.jsdelivr.net/npm/highwayhasher@0.4.3/dist/browser-fat/umd/index_browser_fat.min.js"></script>
  <script>(function() {
    const { HighwayHash } = highwayhasher;
    const keyData = Uint8Array.from(new Array(32).fill(1));
    HighwayHash.loadModule().then((hasher) => {
      const out = hasher.hash64(keyData, Uint8Array.from([0]));
      console.log(out);
    });
  })();
  </script>
</body>
```

And even without build tools there are many ways that we can import highwayhash. For instance, we can target only recent browsers and be able to load highwayhasher more efficiently:

```html
<script type="module">
  import { HighwayHash } from 'https://cdn.jsdelivr.net/npm/highwayhasher@0.4.3/dist/browser-slim/es/index_browser_slim.min.js';

  const hasher = await HighwayHash.loadModule({
    wasm: {
      simd: 'https://cdn.jsdelivr.net/npm/highwayhasher@0.4.3/dist/highwayhasher_wasm_simd_bg.wasm',
      sisd: 'https://cdn.jsdelivr.net/npm/highwayhasher@0.4.3/dist/highwayhasher_wasm_bg.wasm',
    }
  });

  const keyData = Uint8Array.from(new Array(32).fill(1));
  const out = hasher.hash64(keyData, Uint8Array.from([0]));
  console.log(out);
</script>
```

> Also, there's no discussion tab, so I'm adding it here. I'm interested in 32bit hashes. I understand the highway algorithm is 64bit minimum. It wouldn't need to be highway; something like crc32fast to provide the algorithm for a 32bit hash output? Do I fork and work a separate binding for crc32fast or extend highway or is it not a good idea for some reason?

If you want 32bit and highwayhash, you can truncate the result. At this time, I'd rather keep the repo focused on just highwayhash, but I can see a compelling use case for making this library a collection of hashing functions (like [hash-wasm](https://github.com/Daninet/hash-wasm), but with a better API (imo)).

**Comment by davehorner** [comment]
perfect.  your examples are exactly what I was looking for and worked.  As a suggestion, it might be helpful to others to include the basic browser example in the readme or example folder.

the hash-wasm reference; c libs.  I'd rather have a shared crc32 rust implementation with a front end like highwayhash but I also don't see me spending the time to create a new project or understand how to bring in the infrastructure from highwayhash into a crc32 crate. Adding a function and dep to highwayhasher looked like a complexity level I might be able to do...flawed as it may be.  maybe hash-wasm could include a rust implementation...idk, even more unlikely for me to do.

I understand wanting to keep it highway specific.  The thought of truncating had occurred to me but I wonder what the collisions look like and with the added complexity, how much faster the javascript implementation "crc-32" to be or not be.

thank you.

**Comment by nickbabcock** [comment]
> perfect. your examples are exactly what I was looking for and worked. As a suggestion, it might be helpful to others to include the basic browser example in the readme or example folder.

Sounds good, I'll add them

> I understand wanting to keep it highway specific. The thought of truncating had occurred to me but I wonder what the collisions look like and with the added complexity, how much faster the javascript implementation "crc-32" to be or not be.

The performance difference between highwayhasher and crc-32 implementations is intriguing but I haven't run benchmarks comparing the two, so I'm not sure.

The "randomness" of highwayhash output is uniform so you are fine to take 32bit chunks of it.

> the hash-wasm reference; c libs. I'd rather have a shared crc32 rust implementation with a front end like highwayhash but I also don't see me spending the time to create a new project or understand how to bring in the infrastructure from highwayhash into a crc32 crate. Adding a function and dep to highwayhasher looked like a complexity level I might be able to do...flawed as it may be. maybe hash-wasm could include a rust implementation...idk, even more unlikely for me to do.

I'm not sure I understand the motivation. Why does it matter rust vs c if the browser client only receives JS/wasm? Or are you just attracted to the API highwayhasher exposes, where native code is executed in node and JS/Wasm used elsewhere (and it'd be nice if other algorithms are added)?

**Comment by davehorner** [comment]
I'm in a rust codebase and thought it was nice to have highway-rs available via rust and highway via wasm.  
the charting on the highway-rs page is cool.
yes, it would be interesting to see crc32 benched against highway.

sometimes I link together things that don't make sense.
